spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/udodb_admin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: udo
    password: 1234

  flyway:
    enabled: true
    baselineOnMigrate: true
    url: jdbc:mysql://localhost:3306/udodb_admin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    user: udo
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

root:
  id: root
  password: root


